//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBJAM14
{
    
    
    public partial class GameTypes
    {
        
        public static int Type1 = 0;
        
        public static int Type2 = 1;
        
        public static string ValueToName(int value)
        {
            if (value == Type1) return nameof(Type1);
            if (value == Type2) return nameof(Type2);
            return null;
        }
        
        public static void GetNames(int mask, System.Collections.Generic.ICollection<string> collection)
        {
            if ((mask & (1 << Type1)) == (1 << Type1)) collection.Add(nameof(Type1));
            if ((mask & (1 << Type2)) == (1 << Type2)) collection.Add(nameof(Type2));
        }
    }
}
