//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBJAM13
{
    
    
    public partial class EventTypes
    {
        
        public static int Wormhole = 0;
        
        public static int Planet = 1;
        
        public static int Ship = 2;
        
        public static int Asteroid = 3;
        
        public static string ValueToName(int value)
        {
            if (value == Wormhole) return nameof(Wormhole);
            if (value == Planet) return nameof(Planet);
            if (value == Ship) return nameof(Ship);
            if (value == Asteroid) return nameof(Asteroid);
            return null;
        }
        
        public static void GetNames(int mask, System.Collections.Generic.ICollection<string> collection)
        {
            if ((mask & (1 << Wormhole)) == (1 << Wormhole)) collection.Add(nameof(Wormhole));
            if ((mask & (1 << Planet)) == (1 << Planet)) collection.Add(nameof(Planet));
            if ((mask & (1 << Ship)) == (1 << Ship)) collection.Add(nameof(Ship));
            if ((mask & (1 << Asteroid)) == (1 << Asteroid)) collection.Add(nameof(Asteroid));
        }
    }
}
